-- Terraveler seed: Bougainville's first French circumnavigation (1766–1769).
-- Run AFTER schema.sql, in the Supabase SQL editor. Idempotent-ish: clears the
-- voyage's rows first so it can be re-run. Text uses $$…$$ dollar-quoting so
-- apostrophes need no escaping.

-- Clean any previous seed of this voyage.
delete from waypoints  where voyage_id in (select id from voyages where slug = 'boudeuse-1766');
delete from voyages    where slug = 'boudeuse-1766';
delete from navigators where slug = 'bougainville';

-- Navigator
insert into navigators (slug, name, nationality, birth_year, death_year, portrait_url, bio)
values (
  'bougainville',
  $$Louis-Antoine de Bougainville$$,
  $$French$$, 1729, 1811,
  $$https://upload.wikimedia.org/wikipedia/commons/1/1f/Ducreux_-_Louis_Antoine_de_Bougainville.jpg$$,
  $$Louis-Antoine de Bougainville (1729-1811) was a French naval officer, mathematician and explorer, born and died in Paris. After serving as an army officer under Montcalm in Canada during the Seven Years' War, he commanded the first French expedition to circumnavigate the globe (1766-1769) aboard the frigate La Boudeuse and the storeship L'Étoile. His best-selling account, Voyage autour du monde (1771), popularised the image of Tahiti as an earthly paradise and shaped Enlightenment ideas of the 'noble savage'. The climbing plant Bougainvillea and Bougainville Island in the Solomons are named after him.$$
);

-- Voyage
insert into voyages (navigator_id, slug, title, ships, sponsor, purpose, start_date, end_date, summary)
select id, 'boudeuse-1766',
  $$The First French Circumnavigation of the Globe (1766–1769)$$,
  $$La Boudeuse & L'Étoile$$,
  $$King Louis XV of France (French Crown)$$,
  $$To hand the French Îles Malouines (Falkland) colony over to Spain, then cross the Pacific between the tropics in search of new lands and trade routes, completing a scientific circumnavigation carrying naturalists and astronomers.$$,
  $$1766-11-15$$, $$1769-03-16$$,
  $$Departing France in late 1766, Bougainville ceded the Falkland colony to Spain, refitted in the Río de la Plata and Rio de Janeiro, then took 52 days to clear the Strait of Magellan into the Pacific. He reached Tahiti (which he named New Cythera) in April 1768, sailed on through Samoa, Vanuatu and the fringes of the Great Barrier Reef, and struggled hungry through the Louisiade, Solomon and New Britain waters before recovering at Batavia and Mauritius. He returned to Saint-Malo on 16 March 1769 having lost only seven of about 340 men, the first Frenchman to sail around the world.$$
from navigators where slug = 'bougainville';

-- Waypoints
insert into waypoints
  (voyage_id, seq, place_historical, place_modern, latitude, longitude,
   arrival_date, departure_date, date_note, event, diary_excerpt,
   diary_source_citation, diary_source_url, confidence)
select v.id, d.seq, d.place_historical, d.place_modern, d.latitude, d.longitude,
       d.arrival_date, d.departure_date, d.date_note, d.event, d.diary_excerpt,
       d.diary_source_citation, d.diary_source_url, d.confidence
from voyages v
cross join (values
  (1, $$Brest (departure from Nantes)$$, $$Brest, France$$, 48.3904, -4.4861, $$1766-11-21$$, $$1766-12-05$$, $$La Boudeuse left Mindin road (below Nantes) on 15 Nov 1766, was dismasted in a gale, and put into Brest on 21 Nov for repairs; the refitted frigate sailed from Brest on 5 Dec 1766. L'Étoile sailed separately from Rochefort in early Feb 1767.$$, $$Start of the expedition: after being dismasted at sea, the Boudeuse repaired at Brest, exchanged her twelve-pounders for lighter guns, and finally sailed for the Río de la Plata with about 200 men aboard.$$, $$The 5th at noon we got under sail in the road of Brest. I was obliged to cut my cable, because the fresh east-wind and the ebb prevented my tacking about, as I was apprehensive of falling off too near the shore.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part I, ch. I$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (2, $$Montevideo, Río de la Plata$$, $$Montevideo, Uruguay$$, -34.9011, -56.1645, $$1767-01-31$$, $$1767-02-28$$, $$Anchored at Montevideo 31 Jan 1767. The Río de la Plata served as the expedition's base through 1767: the ships left for the Falklands in February, returned, and finally weighed for the Strait of Magellan on 14 Nov 1767.$$, $$Bougainville joined the Spanish frigates here and coordinated the transfer of the Falkland colony with the authorities at Buenos Aires; the estuary served as the expedition's main South Atlantic base and reprovisioning point.$$, $$The 31st, at eleven in the morning, we anchored in Montevideo bay, having four fathom water, with a black, soft, muddy bottom.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part I, ch. I$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (3, $$Isles Malouines (Falkland Islands), Port Louis$$, $$Falkland Islands (Port Louis, East Falkland)$$, -51.5478, -58.0968, $$1767-03-23$$, $$1767-06-02$$, $$Anchored in the great bay 23 Mar 1767; formal handover to Spain 1 Apr; the Spanish frigates carried the remaining colonists to Montevideo on 27 Apr; Bougainville, still awaiting L'Étoile, left the Malouines on 2 Jun 1767.$$, $$Bougainville formally delivered the French colony he had founded (Port Saint-Louis) to Spain, hauling down the French flag and raising the Spanish colours; some colonists stayed under Spanish rule while others embarked for the mainland.$$, $$The first of April I delivered our settlement to the Spaniards, who took possession of it, by planting the Spanish colours, which were saluted at sun-rising and sun-setting from the shore and from the ships.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part I, ch. III$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (4, $$Rio-Janeiro$$, $$Rio de Janeiro, Brazil$$, -22.9068, -43.1729, $$1767-06-21$$, $$1767-07-14$$, $$Saw the Brazilian headlands 20 Jun and anchored at Rio de Janeiro 21 Jun 1767; weighed 14 Jul 1767 to return to the Río de la Plata for provisions.$$, $$Here the Boudeuse finally rendezvoused with the long-awaited storeship L'Étoile, which had been forced to put into Montevideo. The junction of the two ships allowed the Pacific crossing to proceed, though L'Étoile carried far less bread than needed.$$, $$The 20th of June, in the afternoon, we saw the high head-lands of the Brasils; and, on the 21st, we discovered the entrance of Rio-Janeiro.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part I, ch. V$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (5, $$Straits of Magalhaens (Port Galant / Cape Pillar)$$, $$Strait of Magellan, Chile$$, -53.68, -72.02, $$1767-12-05$$, $$1768-01-26$$, $$First sighted Cape Virgins 2 Dec and entered the strait 5–6 Dec 1767; storm-bound for weeks at Port Galant; cleared Cape Pillar into the Pacific about 26 Jan 1768. Forster's text gives the passage as 52 days but not an exact exit date.$$, $$The two ships made a difficult 52-day passage of the Strait of Magellan, met and traded with Patagonians near Cape Virgins, and endured three weeks of storms at Port Galant before a rare fair wind carried them out past Cape Pillar into the Pacific.$$, $$at seven, Cape Pillar was doubled, and at eight we were quite clear of the land, and advancing, all sails set, and with a fine northerly wind, into the westerly ocean.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part I, ch. IX$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (6, $$Taïti (New Cythera / Nouvelle-Cythère)$$, $$Tahiti, French Polynesia$$, -17.6167, -149.3, $$1768-04-06$$, $$1768-04-16$$, $$First contact with Tahitian canoes 4 Apr, anchored off Hitiaʻa (NE coast) 6 Apr, departed 16 Apr 1768. Bougainville arrived less than a year after Samuel Wallis, so he was not the first European to reach Tahiti.$$, $$Bougainville claimed the island for France and named it New Cythera, describing an apparent paradise of abundance and free hospitality. During the brief stay his crew discovered that Jeanne Barret, valet to the naturalist Commerçon, was a woman, and a Tahitian named Ahutoru volunteered to sail with the expedition.$$, $$I thought I was transported into the garden of Eden; we crossed a turf, covered with fine fruit-trees, and interfered by little rivulets, which keep up a pleasant coolness in the air, without any of those inconveniences which humidity occasions.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. III$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (7, $$Archipel des Navigateurs (Isles of the Navigators)$$, $$Samoan Islands$$, -14.0, -171.0, $$1768-05-03$$, $$1768-05-11$$, $$Sighted the eastern Samoan islands 3–11 May 1768. The ships coasted but did not land; the identification of the exact islands is approximate.$$, $$Impressed by islanders who handled their outrigger canoes with extraordinary skill even at speed, Bougainville named the group the Archipelago of the Navigators, a name Samoa retained on European charts for over a century.$$, $$Though we ran seven or eight knots at this time, yet the periaguas sailed round us with the same ease as if we had been at anchor.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. IV$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$approximate$$),
  (8, $$Archipel des Grandes Cyclades (Tierra Austral del Espíritu Santo)$$, $$Vanuatu (Espiritu Santo)$$, -15.4, 167.2, $$1768-05-22$$, $$1768-05-29$$, $$Sailed among the islands (Pentecost, Aurora/Maewo and off Espiritu Santo) roughly 22–29 May 1768; named the group the Great Cyclades. He correctly suspected it was Quirós's 1606 'Espíritu Santo' and that it was islands, not a southern continent.$$, $$Bougainville explored and named the Great Cyclades (modern Vanuatu), passing between Pentecost and Aurora, and confirmed that Quirós's supposed 'Austral land of the Holy Spirit' was an archipelago rather than the great Southern Continent.$$, $$As for ourselves, when we fell in with it, every thing conspired to persuade us that it was the Tierra Austral del Espiritù Santo.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. IV$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$approximate$$),
  (9, $$Shoals east of New Holland (Shoal of Diana)$$, $$Coral Sea, off the outer Great Barrier Reef, Australia$$, -15.0, 148.0, $$1768-06-04$$, $$1768-06-07$$, $$Struck shoals and breakers on the nights of 4–6 Jun 1768 near latitude 15°S; on 6–7 Jun abandoned the westward course and turned NE. Position is an open-sea reckoning and is approximate.$$, $$Sailing west toward the unseen east coast of Australia, Bougainville ran into the reefs and sandbanks fringing the Coral Sea and turned away north-eastward. Had he pressed on he might have discovered the Great Barrier Reef and eastern Australia; instead he steered for known waters.$$, $$This last discovery was the voice of God, and we were obedient to it.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. V$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$approximate$$),
  (10, $$Golfe de la Louisiade; Isle & Bay of Choiseul$$, $$Louisiade Archipelago (PNG) & Solomon Islands (Choiseul)$$, -7.05, 156.95, $$1768-06-25$$, $$1768-07-05$$, $$Doubled Cape Deliverance (SE end of the Louisiade) 26 Jun 1768 after a fortnight trapped in the gulf; reached and were attacked at Choiseul in the Solomon Islands 1–4 Jul 1768. Positions along the track are approximate.$$, $$Half-starved and reduced to eating leather and the ship's animals, the crew fought their way out of the reef-choked Gulf of the Louisiade, then coasted the Solomons, where hostile islanders attacked their boats with arrows near Choiseul; Bougainville avoided landing and later gave his name to Bougainville Island.$$, $$Unhappily hunger, the most cruel of our enemies, was on board. I was obliged to make a considerable diminution in the allowance of bread and pulse.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. V$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$approximate$$),
  (11, $$Port Praslin, New Britain$$, $$Port Praslin, New Ireland, Papua New Guinea$$, -4.68, 152.85, $$1768-07-06$$, $$1768-07-24$$, $$Anchored 6 Jul 1768 at a harbour Bougainville named Port Praslin (on the coast he called New Britain, in fact SE New Ireland); observed a lunar eclipse on 13 Jul to fix the longitude; back to sea in late July 1768 (departure date approximate).$$, $$The exhausted expedition rested and watered at Port Praslin, buried a possession-inscription and used a lunar eclipse to fix its longitude. The crew found a torn English lead plate and a former campsite, traces of Philip Carteret's Swallow which had passed shortly before.$$, $$We have buried an inscription under the very spot where the pendulum had been; and we called this harbour Port Praslin.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. V$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (12, $$Batavia$$, $$Jakarta, Indonesia$$, -6.13, 106.81, $$1768-09-28$$, $$1768-10-16$$, $$Anchored in the road of Batavia 28 Sep 1768 (after touching at Boero/Buru in the Moluccas in early September); set sail 16 Oct 1768, kept short because of the unhealthy season.$$, $$At the Dutch East India Company capital the expedition refitted and reprovisioned, and there Bougainville learned that Wallis and Carteret had preceded him in the Pacific. The unhealthy climate made him keep the stay as brief as possible.$$, $$Thus, after keeping the sea for ten months and a half, we arrived on the 28th of September, 1768, at one of the finest colonies in the universe, where we all looked upon each other as having completed our voyage.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. VII$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (13, $$Isle de France$$, $$Mauritius (Port Louis)$$, -20.1619, 57.4989, $$1768-11-08$$, $$1768-12-22$$, $$Entered the port of the Isle de France 8 Nov 1768; the Boudeuse sailed for the Cape in mid-to-late December 1768. Crossing into the eastern hemisphere the ships found their reckoning a day out and readjusted the date.$$, $$The ships recuperated at the French Indian Ocean colony of the Isle de France (Mauritius). Some personnel, including the naturalist Commerçon and Jeanne Barret, remained on the island, and Bougainville pressed on for home.$$, $$On the 8th, in the morning, we entered the port, where we moored that day.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. IX$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (14, $$Cape of Good Hope (Table Bay)$$, $$Cape Town, South Africa$$, -33.906, 18.4185, $$1769-01-08$$, $$1769-01-17$$, $$Arrived in Table Bay about 8–9 Jan 1769 and departed 17 Jan (Forster's printed '18th' for the arrival appears to be an error for the 8th, since St Helena was sighted on the 29th and Ascension reached 3–4 Feb).$$, $$The Boudeuse revictualled at the Dutch Cape colony in Table Bay, exchanging salutes with the town. Bougainville learned that Carteret's Swallow had left only days before and set off in pursuit down the Atlantic.$$, $$At nine o'clock in the morning we anchored in Table-bay, at the Cape, at the head of the road, and we moored N. N. E. and S. S. W.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. IX$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$),
  (15, $$St. Maloes$$, $$Saint-Malo, France$$, 48.6493, -2.0257, $$1769-03-16$$, null, $$Touched at Ascension (3–4 Feb 1769), sighted Ushant 14 Mar, and entered Saint-Malo on 16 Mar 1769, completing the circumnavigation.$$, $$Bougainville brought the Boudeuse home to Saint-Malo, completing the first French voyage around the world in two years and four months with the loss of only seven men out of about 340, an exceptionally low toll for the era.$$, $$I entered it on the 16th in the afternoon, having lost only seven men, during two years and four months, which were expired since we had left Nantes.$$, $$Bougainville, A Voyage Round the World, trans. J. R. Forster (1772), Part II, ch. IX$$, $$https://www.gutenberg.org/cache/epub/73429/pg73429.txt$$, $$certain$$)
) as d(seq, place_historical, place_modern, latitude, longitude, arrival_date, departure_date, date_note, event, diary_excerpt, diary_source_citation, diary_source_url, confidence)
where v.slug = 'boudeuse-1766';

-- Sources (voyage-level bibliography)
insert into sources (voyage_id, author, title, year, url)
select v.id, s.author, s.title, s.year, s.url
from voyages v
cross join (values
  ($$Louis-Antoine de Bougainville (trans. John Reinhold Forster)$$, $$A Voyage Round the World (1772 English edition)$$, 1772, $$https://www.gutenberg.org/ebooks/73429$$),
  ($$Louis-Antoine de Bougainville$$, $$Voyage autour du monde (French original)$$, 1771, $$https://archive.org/details/voyageautourdumo00boug$$)
) as s(author, title, year, url)
where v.slug = 'boudeuse-1766';
