import json
import uuid
from dataclasses import dataclass, replace
from typing import Optional

from datetime import datetime

from axis.events import Event, EventType, Json, parse_timestamp

# GraphState never generates time.
# Execution timestamps are generated by the Runner.
# Domain-specific timestamps may be provided by Nodes.

# EventType lives in axis.events; it is re-exported here (not redefined) so
# there is exactly one enum and one Event class in the kernel. A second copy
# is how a trace ends up unable to deserialize itself — see Runner.


def _probe_json(value: Json, where: str) -> None:
    """Fail at write time, pointing at the offending key — not at persist
    time, three layers away, with a bare 'not JSON serializable'."""
    try:
        json.dumps(value)
    except TypeError as exc:
        raise TypeError(f"{where} is not JSON-serializable: {exc}") from exc


@dataclass(frozen=True)
class Fact:
    key: str
    value: Json
    source: str
    timestamp: datetime

    def to_dict(self) -> dict:
        return {
            "key": self.key,
            "value": self.value,
            "source": self.source,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Fact":
        return cls(
            key=data["key"],
            value=data["value"],
            source=data["source"],
            timestamp=parse_timestamp(data["timestamp"]),
        )


@dataclass(frozen=True)
class Decision:
    description: str
    timestamp: datetime

    def to_dict(self) -> dict:
        return {
            "description": self.description,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Decision":
        return cls(
            description=data["description"],
            timestamp=parse_timestamp(data["timestamp"]),
        )


@dataclass(frozen=True)
class Rejection:
    description: str
    reason: str
    timestamp: datetime

    def to_dict(self) -> dict:
        return {
            "description": self.description,
            "reason": self.reason,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Rejection":
        return cls(
            description=data["description"],
            reason=data["reason"],
            timestamp=parse_timestamp(data["timestamp"]),
        )


@dataclass(frozen=True)
class GraphState:
    trace_id: str
    intent: Optional[str]
    facts: tuple[Fact, ...]
    decisions: tuple[Decision, ...]
    rejections: tuple[Rejection, ...]
    events: tuple[Event, ...]

    def to_dict(self) -> dict:
        # Field probes give a precise message for the common case (a bad
        # Fact.value or Event.metadata).
        for f in self.facts:
            _probe_json(f.value, f"Fact({f.key!r}).value")
        for e in self.events:
            _probe_json(
                e.metadata,
                f"Event({e.event_type.value!r}, node_name={e.node_name!r}).metadata",
            )

        data = {
            "trace_id": self.trace_id,
            "intent": self.intent,
            "facts": [f.to_dict() for f in self.facts],
            "decisions": [d.to_dict() for d in self.decisions],
            "rejections": [r.to_dict() for r in self.rejections],
            "events": [e.to_dict() for e in self.events],
        }

        # Whole-result probe as a catch-all: Decision/Rejection fields are
        # typed str but nothing enforces that at runtime, so this is what
        # catches an object() in a Decision.description before it becomes
        # an anonymous json.dumps failure three layers away at persist time.
        try:
            json.dumps(data)
        except TypeError as exc:
            raise TypeError(
                f"GraphState({self.trace_id!r}).to_dict() is not JSON-serializable: {exc}. "
                "The field probes only check Fact.value and Event.metadata — this is the "
                "catch-all for everything else (e.g. a non-str Decision/Rejection field)."
            ) from exc

        return data

    @classmethod
    def from_dict(cls, data: dict) -> "GraphState":
        return cls(
            trace_id=data["trace_id"],
            intent=data.get("intent"),
            facts=tuple(Fact.from_dict(f) for f in data.get("facts", [])),
            decisions=tuple(Decision.from_dict(d) for d in data.get("decisions", [])),
            rejections=tuple(Rejection.from_dict(r) for r in data.get("rejections", [])),
            events=tuple(Event.from_dict(e) for e in data.get("events", [])),
        )

    def to_json(self) -> str:
        """Thin wrapper over to_dict — the JSON boundary is the kernel's job."""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, data: str) -> "GraphState":
        return cls.from_dict(json.loads(data))

    # Every with_* returns a sibling via dataclasses.replace — five
    # hand-written copy-constructors collapse to one line each.
    # Tuple append is O(n) per with_*, so a trace build is O(n^2); that's
    # fine at kernel scale (a run has nodes, not millions of events) and is
    # deliberate, not an oversight.

    def with_intent(self, intent: str) -> "GraphState":
        return replace(self, intent=intent)

    def with_fact(self, fact: Fact) -> "GraphState":
        return replace(self, facts=self.facts + (fact,))

    def with_decision(self, decision: Decision) -> "GraphState":
        return replace(self, decisions=self.decisions + (decision,))

    def with_rejection(self, rejection: Rejection) -> "GraphState":
        return replace(self, rejections=self.rejections + (rejection,))

    def with_event(self, event: Event) -> "GraphState":
        return replace(self, events=self.events + (event,))

    def fact(self, key: str, default=None):
        """Latest value for `key`. Facts are history — a key written twice
        keeps both entries; this returns the most recent one, or `default`
        if the key was never set."""
        for f in reversed(self.facts):
            if f.key == key:
                return f.value
        return default

    @staticmethod
    def empty(trace_id: str) -> "GraphState":
        return GraphState(
            trace_id=trace_id,
            intent=None,
            facts=(),
            decisions=(),
            rejections=(),
            events=(),
        )

    @classmethod
    def new(cls, prefix: str = "") -> "GraphState":
        """Mint a fresh run identity: `{prefix}-{uuid4().hex[:12]}`, or a
        bare hex id if no prefix is given. Replaces the three hand-rolled,
        second-resolution trace_id formats this kernel's consumers invented
        (and which collide on a same-second rerun)."""
        suffix = uuid.uuid4().hex[:12]
        trace_id = f"{prefix}-{suffix}" if prefix else suffix
        return cls.empty(trace_id)
